version: 2.1
description: CircleCI tests

jobs:
  build:
    docker:
    - image: mrupgrade/kta-webapp-flask
    - image: mrupgrade/kta-webapp-gunicorn
    steps:
    - checkout
    - run: echo "hello world"


workflow:
  version: 2.1
  pipe1:
    jobs:
    - build