version: 2.1
description: CircleCI tests

jobs:
  job1_test:
    docker:
    - image: debian
    steps:
    - checkout
    - run: echo "hello world"

  job_echo:
    docker:
    - image: debian
    steps:
    - run: "hello from echo job"

_job_list: &jobList
- job_echo

workflows:
  version: 2.1
  pipe1:
    jobs:
    - job1_test
    - job_echo
