version: 2.1
description: CircleCI tests

#orbs:
#  ec: mrupgrade/echo-test@dev:0.0.1

jobs:
  job1_test:
    docker:
    - image: debian
    steps:
    - checkout
    - run: echo "hello world"
    - run: echo ${CIRCLE_WORKFLOW_ID}


workflows:
  version: 2.1
  pipe1:
    jobs:
    - job1_test
#    - ec/echo
#    -
